server:
  port: 8243

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/emailservice
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: EMAIL-SERVICE
  config:
    import: configserver:http://localhost:9296
  main:
    allow-circular-references: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: email
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    topic:
      name: email_topics
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password: 
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true